---
controller_execution_environments:
  - name: "Minimal execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:348e84ee0f325ab686e84a5eedace008e14d4b5f36e1c9bc1fc727c6afc4c957"
    pull: ""
  - name: "Default execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:da9d6d4ed8b2b86ca7ef6cd0eeaa996c1e2fe7427f0d31baf7a576248940295d"
    pull: ""
  - name: "Control Plane Execution Environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:da9d6d4ed8b2b86ca7ef6cd0eeaa996c1e2fe7427f0d31baf7a576248940295d"
    pull: ""
...
